import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import organizationsRouter from "./organizations";
import membersRouter from "./members";
import savingsRouter from "./savings";
import loansRouter from "./loans";
import payrollRouter from "./payroll";
import walletsRouter from "./wallets";
import riskRouter from "./risk";
import notificationsRouter from "./notifications";
import reportsRouter from "./reports";
import auditRouter from "./audit";
import rolesRouter from "./roles";
import supportRouter from "./support";
import settingsRouter from "./settings";
import featureFlagsRouter from "./feature-flags";
import securityRouter from "./security-center";
import excelRouter from "./excel";
import investmentsRouter from "./investments";
import systemRouter from "./system";
import scheduledNotificationsRouter from "./scheduled-notifications";
import backupsRouter from "./backups";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(dashboardRouter);
router.use(organizationsRouter);
router.use(membersRouter);
router.use(savingsRouter);
router.use(loansRouter);
router.use(payrollRouter);
router.use(walletsRouter);
router.use(riskRouter);
router.use(notificationsRouter);
router.use(reportsRouter);
router.use(auditRouter);
router.use(rolesRouter);
router.use(supportRouter);
router.use(settingsRouter);
router.use(featureFlagsRouter);
router.use(securityRouter);
router.use(excelRouter);
router.use(investmentsRouter);
router.use(systemRouter);
router.use(scheduledNotificationsRouter);
router.use(backupsRouter);

export default router;
